{{- $host := required "gateway.host must be set" .Values.gateway.host -}}
{{- $listenerName := ternary "https" "http" .Values.gateway.tls.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hotel-booking
spec:
  parentRefs:
    - name: hotel-booking
      sectionName: {{ $listenerName }}
  hostnames:
    - {{ $host | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/reservations"
      backendRefs:
        - name: reservations
          port: 3004
    - matches:
        - path:
            type: PathPrefix
            value: "/auth"
      backendRefs:
        - name: auth-http
          port: 3003
    - matches:
        - path:
            type: PathPrefix
            value: "/users"
      backendRefs:
        - name: auth-http
          port: 3003
