apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      automountServiceAccountToken: false
      containers:
        - image: '{{ .Values.images.registry }}/notifications/production:{{ required "images.tag is required" .Values.images.tag }}'
          imagePullPolicy: "{{ .Values.images.pullPolicy }}"
          name: notifications
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
              ephemeral-storage: 128Mi
            limits:
              memory: 256Mi
          env:
            - name: PORT
              value: '3000'

            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: google
                  key: smtpUser

            - name: GOOGLE_OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: google
                  key: clientId

            - name: GOOGLE_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: google
                  key: clientSecret

            - name: GOOGLE_OAUTH_REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: google
                  key: refreshToken
          ports:
            - containerPort: 3000
