apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      automountServiceAccountToken: false
      containers:
        - image: '{{ .Values.images.registry }}/auth/production:{{ required "images.tag is required" .Values.images.tag }}'
          imagePullPolicy: "{{ .Values.images.pullPolicy }}"
          name: auth
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
              ephemeral-storage: 128Mi
            limits:
              memory: 256Mi
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: connectionString

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: jwtSecret

            - name: JWT_EXPIRATION
              value: '604800000'

            - name: TCP_PORT
              value: '3002'

            - name: HTTP_PORT
              value: '3003'
          ports:
            - containerPort: 3002
            - containerPort: 3003
